did zsh and kitty edits, create a new script too

diff --git a/scripts/.local/bin/fix-all-git-authors b/scripts/.local/bin/fix-all-git-authors
--- a/scripts/.local/bin/fix-all-git-authors
+++ b/scripts/.local/bin/fix-all-git-authors
@@ -1,19 +1,35 @@
-#!/bin/sh
- 
-git filter-branch --env-filter '
- 
-OLD_EMAIL="31601170+scottross123@users.noreply.github.com"
-CORRECT_NAME="Scott Ross"
-CORRECT_EMAIL="sross@manh.com"
+#!/bin/bash
 
-if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
+if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
 then
-    export GIT_COMMITTER_NAME="$CORRECT_NAME"
-    export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
+  echo "error: missing parameters, run script like 'fix-authors [OLD_EMAIL] [CORRECT_NAME] [CORRECT_EMAIL]'"
+  exit 1
 fi
-if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
+
+OLD_EMAIL=$1
+CORRECT_NAME=$2
+CORRECT_EMAIL=$3
+
+
+read -p "WARNING this script will modify ALL git history. Do you wish to proceed? (Y/n)" CHOICE
+
+# NOTE look into using git filter-repo instead
+
+if [ "$CHOICE" == "Y" ]
 then
-    export GIT_AUTHOR_NAME="$CORRECT_NAME"
-    export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
+  git filter-branch --env-filter '
+
+  if [ "$GIT_COMMITTER_EMAIL" = "$OLD_EMAIL" ]
+  then
+      export GIT_COMMITTER_NAME="$CORRECT_NAME"
+      export GIT_COMMITTER_EMAIL="$CORRECT_EMAIL"
+  fi
+  if [ "$GIT_AUTHOR_EMAIL" = "$OLD_EMAIL" ]
+  then
+      export GIT_AUTHOR_NAME="$CORRECT_NAME"
+      export GIT_AUTHOR_EMAIL="$CORRECT_EMAIL"
+  fi
+  ' --tag-name-filter cat -- --branches --tags
+else
+  exit 0
 fi
-' --tag-name-filter cat -- --branches --tags
